# fly.toml app configuration file generated for flyio-surrealdb on 2026-08-04T21:21:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flyio-surrealdb'
primary_region = 'nrt'

[processes]
app = "start --bind 0.0.0.0:8000 surrealdb:/mydata/mydatabase.db"

[mounts]
source = "surreal_data"
destination = "/mydata"

[http_service]
auto_start_machines = true
auto_stop_machines = "stop"
force_https = true
internal_port = 8000
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '256MB'
